FROM ghcr.io/cyber-dojo-languages/javascript-node:3879b15
LABEL maintainer=jon@jaggersoft.com

RUN mkdir /etc/jest
WORKDIR /etc/jest
COPY package.json .
RUN npm install

COPY red_amber_green.rb /usr/local/bin
